export const GET_PODUCTS_REQUEST = 'GET_PODUCTS_REQUEST';
export const GET_PODUCTS_SUCCESS = 'GET_PODUCTS_SUCCESS';
export const GET_PODUCTS_FAILED = 'GET_PODUCTS_FAILED';

export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_FAILED = 'ORDER_FAILED';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';